### ISSUE TITLE
Wont install - missing dependency

### ISSUE THREAD

**Issue by Geraintjdotocom** [simonarnell/homebridge-solis#13]
Hi!

Would love to integrate my solis inverter into homekit to trigger items when I am generating more than I am using.

However It wont install on homebridge. I believe the below dependency may have changed?

[solis-inverter](https://www.npmjs.com/package/solis-inverter)

Thanks!

GEr

**Comment by simonarnell** [comment]
Hi GEr,

The dependency is actually on [ssh://git@github.com:fss/solis-inverter.git](https://github.com/fss/solis-inverter), not https://www.npmjs.com/package/solis-inverter. The former being pulled by npm using git over ssh. 

Can you confirm that you have an ssh client installed on your host?

**Comment by Geraintjdotocom** [comment]
Hi Simon,

Thanks for the reply. I’m trying to install it via homebridge UI which gives the attached error. I’m not as offay with SSH installs on a mac and will have to see if I can figure it out!

Thanks again

Ger

<img width="880" alt="Screenshot 2022-03-23 at 10 32 33" src="https://user-images.githubusercontent.com/101974102/159680682-607fa8a7-7c1d-4eac-bc20-a4e9b5bcd33c.png">

**Comment by Geraintjdotocom** [comment]
Resolved. My XCODE installation had broken and I was having the issue.

Installed now. My apologies.
