### ISSUE TITLE
Ginlong Solis Inverter Datastick

### ISSUE THREAD

**Issue by bartgabriels** [simonarnell/homebridge-solis#5]
Can't retrieve info:

[24/02/2021, 16:32:27] [Solis PV Inverter - Loft] {"lastSeen":1614180747975,"inverter":{"model":null,"serial":null,"firmwareMain":null,"firmwareSlave":null},"logger":{"serial":null,"version":null,"mode":null,"ap":{"ssid":null,"ip":null,"mac":null},"sta":{"ssid":null,"ip":null,"mac":null,"rssi":null}},"remoteServer":{"a":false,"b":false},"power":0,"energy":{"today":0,"total":0}}

This is de JSON reply I get manually, from the stick directly
{"g_sn":901990927,"g_ver":"ME-121001-V1.0.6(2016-10-111136)","time":1614181040,"g_time":28239,"g_err":0,"mac":"bc-54-f9-fa-ee-ca","auto_ip":0,"ip":"10.0.0.102","sub":"255.255.255.0","gate":"10.0.0.1","auto_dns":0,"dns":"208.67.222.222","dns_bak":"208.67.222.222","i_status":16,"i_type":1281,"i_num":1,"i_sn":"0003700171073020","i_ver_m":"","i_ver_s":"","i_modle":"","i_pow":"","i_pow_n":475,"i_eday":"19.10","i_eall":"22202.0","i_alarm":"","i_last_t":0,"l_a_agr":0,"l_a_ip":"47.88.8.200","l_a_port":10000}

This is the config:
        {
            "name": "Solis PV Inverter - Loft",
            "username": "",
            "password": "",
            "hostname": "10.0.0.102",
            "interval": 30,
            "accessory": "Solis PV Inverter Homebridge Plugin"
        }

**Comment by simonarnell** [comment]
Hi @bartgabriels, unfortunately it seems Solis have changed the message format between datastick  fw versions. I don't actually perform the processing within this project, but instead rely on [fss/solis-inverter](https://github.com/fss/solis-inverter). I suggest you raise an issue with the upstream project.
